// Generated by LiveScript 1.5.0
(function(){
  var port, bodyParser, requireLs, http, readFileSync, verifyRecord, express, cors, content, verify, app;
  port = require('./config.json').port;
  bodyParser = require('body-parser');
  requireLs = require('require-ls');
  http = require('http');
  readFileSync = require('fs').readFileSync;
  verifyRecord = require('./verify-record.ls');
  express = require('express');
  cors = require('cors');
  content = function(req, res){
    res.writeHead(200, {
      'Content-Type': 'text/html'
    });
    return res.end(readFileSync('./dapp/.compiled/client-index.html', 'utf8'));
  };
  verify = function(req, res){
    return verifyRecord(req.headers.name, req.headers.record, function(err, accessKey){
      if (err != null || accessKey == null) {
        return res.status(400).end(err);
      }
      return res.send(accessKey);
    });
  };
  app = express();
  app.use(cors());
  app.post('/', verify);
  app.get('/', content);
  app.listen(port != null ? port : 80);
  process.on('uncaughtException', function(err){
    return console.log(err);
  });
}).call(this);
