// Generated by LiveScript 1.5.0
(function(){
  var port, bodyParser, requireLs, http, readFileSync, getIndex, server;
  port = require('./config.json').port;
  bodyParser = require('body-parser');
  requireLs = require('require-ls');
  http = require('http');
  readFileSync = require('fs').readFileSync;
  getIndex = function(){
    return readFileSync('./dapp/.compiled/client-index.html', 'utf8');
  };
  server = http.createServer(function(req, res){
    res.writeHead(200, {
      'Content-Type': 'text/html'
    });
    return res.end(getIndex());
  });
  server.listen(port != null ? port : 8080);
  process.on('uncaughtException', function(err){
    return console.log(err);
  });
}).call(this);
