// Generated by LiveScript 1.5.0
(function(){
  var observer, observable, react, ref$, updateRouter, onHrefClick, pages, notFound, toString$ = {}.toString;
  observer = require('mobx-react').observer;
  observable = require('mobx').observable;
  react = require('react');
  ref$ = require('./router.ls'), updateRouter = ref$.updateRouter, onHrefClick = ref$.onHrefClick;
  pages = require('./pages.ls');
  notFound = function(){
    return react.createElement('div', {
      className: 'content'
    }, ' Page Not Found');
  };
  module.exports = function(arg$){
    var store, io, currentPage, ref$, children;
    store = arg$.store, io = arg$.io;
    currentPage = (ref$ = pages[store.current.page]) != null ? ref$ : notFound;
    if (toString$.call(currentPage).slice(8, -1) !== 'Function') {
      throw store.current.page + " is not a page";
    }
    return react.createElement('div', {
      className: 'app app1798369022'
    }, children = currentPage({
      store: store
    }));
  };
}).call(this);
