// Generated by LiveScript 1.5.0
(function(){
  var observer, ref$, observable, toJS, transaction, render, react, app, objToPairs, pairsToObj, map, each, concat, filter, find, dataScheme, restoreRouter, goto, reload, parse, stringify, store, Main;
  observer = require('mobx-react').observer;
  ref$ = require('mobx'), observable = ref$.observable, toJS = ref$.toJS, transaction = ref$.transaction;
  render = require('react-dom').render;
  react = require('react');
  app = require('./app.ls');
  ref$ = require('prelude-ls'), objToPairs = ref$.objToPairs, pairsToObj = ref$.pairsToObj, map = ref$.map, each = ref$.each, concat = ref$.concat, filter = ref$.filter, find = ref$.find;
  dataScheme = require('./data-scheme.ls');
  ref$ = require('./router.ls'), restoreRouter = ref$.restoreRouter, goto = ref$.goto, reload = ref$.reload;
  parse = JSON.parse, stringify = JSON.stringify;
  store = observable(dataScheme);
  Main = observer(function(arg$){
    var store;
    store = arg$.store;
    return app({
      store: store
    });
  });
  window.onpopstate = function(event, state){
    return goto(event.state.page, store);
  };
  restoreRouter(store);
  window.onload = function(){
    return render(react.createElement(Main, {
      store: store
    }), document.body.appendChild(document.createElement('app')));
  };
}).call(this);
