// Generated by LiveScript 1.5.0
(function(){
  var ref$, objToPairs, pairsToObj, map, dasherize, addresses, page, current;
  ref$ = require('prelude-ls'), objToPairs = ref$.objToPairs, pairsToObj = ref$.pairsToObj, map = ref$.map, dasherize = ref$.dasherize;
  addresses = require('../blockchain/.out/addresses.json');
  page = 'loading';
  current = {
    page: page
  };
  module.exports = {
    current: current
  };
}).call(this);
