// Generated by LiveScript 1.5.0
(function(){
  var react, standard, chooseRopsten, chooseMainnet, showExample;
  react = require('react');
  standard = function(){
    return i.zmdi.zmdiError;
  };
  chooseRopsten = function(){
    return react.createElement('img', {
      src: "http://res.cloudinary.com/thedapper/image/upload/v1519312076/metamask-ropsten-mainnet.gif"
    });
  };
  chooseMainnet = function(){
    return react.createElement('img', {
      src: "http://res.cloudinary.com/thedapper/image/upload/v1519312075/metamask-mainnet-ropsten.gif"
    });
  };
  showExample = function(message){
    switch (false) {
    case message != null:
      return null;
    case !(message.indexOf("Your MetaMask is pointing to 'mainnet' network") > -1):
      return chooseRopsten();
    case !(message.indexOf("Your MetaMask is pointing to 'ropsten' network") > -1):
      return chooseMainnet();
    default:
      return standard();
    }
  };
  module.exports = function(arg$){
    var store, err, message, ref$, children;
    store = arg$.store;
    err = store.current.error;
    message = (ref$ = err.message) != null ? ref$ : err;
    return react.createElement('div', {
      className: 'error error-1687757096'
    }, children = [
      react.createElement('div', {
        className: 'head'
      }, children = showExample(message)), react.createElement('div', {
        className: 'title'
      }, ' Oops!'), react.createElement('div', {
        className: 'message'
      }, ' ' + message)
    ]);
  };
}).call(this);
