// Generated by LiveScript 1.5.0
(function(){
  var Web3, ref$, ethNet, guestAccount, networks, ownerAddress, web3Provider, initCustom, initMetamask;
  Web3 = require('web3');
  ref$ = require('./config.json'), ethNet = ref$.ethNet, guestAccount = ref$.guestAccount;
  networks = require('./networks.json');
  ref$ = networks[ethNet], ownerAddress = ref$.ownerAddress, web3Provider = ref$.web3Provider;
  initCustom = function(ownerAddress){
    var web3;
    web3 = new Web3(new Web3.providers.HttpProvider(web3Provider));
    web3.eth.defaultAccount = ownerAddress;
    return web3;
  };
  initMetamask = function(){
    var ref$, ref1$;
    if ((typeof window != 'undefined' && window !== null ? (ref$ = window.web3) != null ? (ref1$ = ref$.eth) != null ? ref1$.defaultAccount : void 8 : void 8 : void 8) != null) {
      return window.web3;
    }
    if (typeof window != 'undefined' && window !== null) {
      return initCustom(guestAccount);
    }
  };
  module.exports = (ref$ = initMetamask()) != null
    ? ref$
    : initCustom(ownerAddress);
}).call(this);
