// Generated by LiveScript 1.5.0
(function(){
  var main, error;
  main = require('./main.ls');
  error = require('./error.ls');
  module.exports = {
    main: main,
    error: error
  };
}).call(this);
