// Generated by LiveScript 1.5.0
(function(){
  module.exports = function(cb){
    if (typeof web3 == 'undefined' || web3 === null) {
      return cb(null);
    }
    return web3.version.getNetwork(function(err, netId){
      var host, ref$, network;
      host = (ref$ = location.host.split('.')) != null ? ref$[0] : void 8;
      network = (function(){
        switch (false) {
        case netId !== '1':
          return 'mainnet';
        case netId !== '3':
          return 'ropsten';
        default:
          return 'ganache';
        }
      }());
      if (host !== network) {
        return cb("Your MetaMask is pointing to '" + network + "' network but this game requires '" + host + "'. Please choose '" + host + "' network in MetaMask.");
      }
      return cb(null);
    });
  };
}).call(this);
